export PROJECT=Final
export BUCKET=LoadTesting_Final
AMI="ami-fce3c696"
KeyPairName="key_Gunjan"
SecurityGroup="sg-ee751395"
InstanceType="t2.micro"
Subnet="subnet-a28a3dfa"
NoOfInstances=1
export AMI=skfn
export InstanceType=db
export Subnet=bd
export SecurityGroup=bd
export KeyPairName=bd
export NoOfInstances=db
